[project]
site_name = "Patina"
site_url = "https://stacksmiths.github.io/zensical-patina/"
repo_url = "https://github.com/stacksmiths/zensical-patina"
repo_name = "stacksmiths/zensical-patina"

nav = [
  { "Overview" = "index.md" },
  { "Usage" = "usage.md" },
]

[project.theme]
name = "patina"
language = "en"
features = [
  "content.code.copy",
  "navigation.footer",
  "navigation.top",
  "search.highlight",
]

[project.markdown_extensions]
admonition = {}
attr_list = {}
md_in_html = {}
pymdownx.highlight = {}
pymdownx.superfences = {}
toc.permalink = true
